// l2bridge/src/App.svelte
<script lang="ts">
	import type { ITokenContextData } from '@tokenscript/card-sdk/dist/types';
	import context from './lib/context';
	import NotFound from './routes/NotFound.svelte';
	import Bridge from './routes/Bridge.svelte';
	import './styles.css';

	let token: ITokenContextData;
	let tsViewerType;

	let page: Page;

	page = Bridge;
	console.log("page = Bridge... 0")
	function routeChange() {
		const card: string = new URLSearchParams(document.location.hash.substring(1)).get('card') ?? '';
		console.log("page = Bridge")
		page = Bridge;
	}

	if (tokenscript.tokens.data.currentInstance) {
		context.setToken(tokenscript.tokens.data.currentInstance);
	}

	tokenscript.tokens.dataChanged = async (oldTokens, updatedTokens, cardId) => {
		context.setToken(updatedTokens.currentInstance);
		token = updatedTokens.currentInstance;

		if (tokenscript.tokens.data.currentInstance) {
			context.setToken(tokenscript.tokens.data.currentInstance);
			token = tokenscript.tokens.data.currentInstance
			console.log({token})
		}
		routeChange();
	};
</script>

<svelte:window on:hashchange={routeChange} />

<div>
	<div id="token-container">
		<svelte:component this={page} />
	</div>
</div>

// tapp-for-opensea/tapp/src/App.tsx
import React, { useState, useEffect, FC } from "react";
import { NotFound } from "./cards/NotFound";
import { ITokenContextData } from "@tokenscript/card-sdk/dist/types";
import { Buy } from "./cards/Buy";

const App: FC = () => {
  // add TokenScript Card views here
  enum CardName {
    Buy = "#buy",
    NotFound = "#notFound",
  }

  const [CurrentPageName, setCurrentPageName] = useState<CardName>(
    CardName.Buy
  );
  const [token, setToken] = useState<ITokenContextData>();

  const mapCardName = (hashString: string | null): CardName => {
    console.log("hashString--",hashString)
    if (!hashString) return CardName.NotFound;
    
    const params = new URLSearchParams(hashString.replace('#', ''));
    const card = params.get('card');
    console.log('card--',card)

    switch (card) {
      case 'Buy':{
        return CardName.Buy;
      }
      default:
        return CardName.NotFound;
    }


  };

  const cardComponents: { [key in CardName]: React.FC } = {
    [CardName.Buy]: Buy,
    [CardName.NotFound]: NotFound,
  };

  const CurrentPage = cardComponents[CurrentPageName];

  useEffect(() => {
    const routeChange = () => {
      console.log('App',document.location)
      const mappedCardName = mapCardName(document.location.hash);
      setCurrentPageName(mappedCardName);
    };

    tokenscript.tokens.dataChanged = (prevTokens, newTokens, id) => {
      setToken(newTokens.currentInstance);
    };

    if (tokenscript.tokens.data.currentInstance) {
      setToken(tokenscript.tokens.data.currentInstance);
    }

    window.addEventListener("hashchange", routeChange);
    routeChange(); // Handle initial load

    return () => {
      window.removeEventListener("hashchange", routeChange);
    };
  }, []);

  return <CurrentPage token={token} />;
};

export default App;
