// buy-on-uniswap/src/App.tsx
import React, { useState, useEffect, FC } from "react";
import { Buy } from "./cards/Buy";
import { NotFound } from "./cards/NotFound";
import { ITokenContextData } from "@tokenscript/card-sdk/dist/types";

const App: FC = () => {
	enum CardName {
		Buy = "Buy",
		NotFound = "NotFound",
	}

	const [CurrentPage, setCurrentPage] = useState<React.FC>(() => Buy);
	const [token, setToken] = useState<ITokenContextData>();
	const [referralCode, setReferralCode] = useState<string | null>(null);

	const routingMap: Record<string, React.FC> = {
		[CardName.Buy]: Buy,
		[CardName.NotFound]: NotFound,
	};

	const routeChange = () => {
		const params = new URLSearchParams(window.location.hash.substring(1));
		const card = params.get("card");
		const code = params.get("referralCode");

		const SelectedComponent = routingMap[card as CardName] || NotFound;

		setCurrentPage(() => SelectedComponent);
		if(code) setReferralCode(code);
	};

	useEffect(() => {
		tokenscript.tokens.dataChanged = (prevTokens, newTokens, id) => {
			setToken(newTokens.currentInstance);
		};

		if (tokenscript.tokens.data.currentInstance) {
			setToken(tokenscript.tokens.data.currentInstance);
		}

		window.addEventListener("hashchange", routeChange);
		routeChange(); // Initial load

		return () => {
			window.removeEventListener("hashchange", routeChange);
		};
	}, []);

	return <CurrentPage token={token} referralCode={referralCode} />;
};

export default App;

// treasure-box/src/App.svelte
<script lang="ts">
	import type { ITokenContextData } from '@tokenscript/card-sdk/dist/types';
	import context from './lib/context';
	import NotFound from './routes/NotFound.svelte';
	import TreasureBox from './routes/TreasureBox.svelte';
	import TLinkRequired from './routes/TLinkRequired.svelte';

	let token: ITokenContextData;
	let tsViewerType;

	let page: Page;

	tsViewerType = new URLSearchParams(document.location.hash.substring(1)).get('tsViewerType') ?? 'default'

	function routeChange() {
		const card: string = new URLSearchParams(document.location.hash.substring(1)).get('card') ?? '';
		page = tsViewerType.indexOf("tlink") === 0 ? TreasureBox : TLinkRequired;
		// page = TreasureBox;
	}

	if (tokenscript.tokens.data.currentInstance) {
		context.setToken(tokenscript.tokens.data.currentInstance);
	}

	tokenscript.tokens.dataChanged = async (oldTokens, updatedTokens, cardId) => {
		context.setToken(updatedTokens.currentInstance);
		token = updatedTokens.currentInstance;

		if (tokenscript.tokens.data.currentInstance) {
			context.setToken(tokenscript.tokens.data.currentInstance);
		}

		routeChange();
	};
</script>

<svelte:window on:hashchange={routeChange} />

<div>
	<div id="token-container">
		<svelte:component this={page} />
	</div>
</div>
